server:
  port: 9000
  servlet.context-path: /travel

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa.database-platform: org.hibernate.dialect.H2Dialect

client-id: travel-api-client
password: psw
